In [1]:
import numpy as np

In [2]:
v1 = np.array([[np.sqrt(3)], [1]])
v2 = np.array([[1], [1]])
inner_result = np.vdot(v1, v2)
print(inner_result)

2.732050807568877


In [3]:
a = np.array([[1, 4], [5, 6]])
a.shape

(2, 2)

In [4]:
v1=np.array([[1 + 2j],[1]])
v2=np.array([[1 - 1j],[1]])
inner_result=np.vdot(v1,v2)
print(inner_result)

-3j


In [5]:
import numpy as np
v1=np.array([[2],[1+1j]])
print(v1)
# from sklearn.preprocessing import normalize
v2 = v1/np.linalg.norm(v1)
print(v2)

[[2.+0.j]
 [1.+1.j]]
[[0.81649658+0.j        ]
 [0.40824829+0.40824829j]]


In [6]:
np.linalg.norm(v1)

2.449489742783178

In [7]:
sigmax=np.array([[0,1],[1,0]])
print(sigmax)
eigenvalues, eigenvectors = np.linalg.eig(sigmax)
print(eigenvalues)
print(eigenvectors)

[[0 1]
 [1 0]]
[ 1. -1.]
[[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]


In [8]:
plus = np.array([[1/np.sqrt(2)], [1/np.sqrt(2)]])
eigenvec0 = np.array([[1], [0]])
np.dot(plus.T,np.dot(np.dot(eigenvec0, eigenvec0.T), plus))

array([[0.5]])

In [27]:
f = np.array([[0], [1]])
e = np.array([[1], [0]])
g = np.array([[1/np.sqrt(2)], [1j/np.sqrt(2)]])

np.kron(g, f + e)

array([[0.70710678+0.j        ],
       [0.70710678+0.j        ],
       [0.        +0.70710678j],
       [0.        +0.70710678j]])

In [29]:
np.tensordot(f, g, axes=0)

array([[[[0.        +0.j        ],
         [0.        +0.j        ]]],


       [[[0.70710678+0.j        ],
         [0.        +0.70710678j]]]])

In [20]:
np.kron(g, f) + np.kron(g, e) == np.kron(g, f + e)

array([[ True],
       [ True],
       [ True],
       [ True]])

In [25]:
f = np.array([[1], [1]])
e = np.array([[0], [1]])
g = np.array([[1j], [1j]])
k = np.array([[1j], [1]])


# Tensor product first and then inner in higher space
scalar1 = np.dot(np.kron(f, g).T, np.kron(e, k))

# Inner product multiply and sum

scalar2 = np.dot(f.T, e) * np.dot(g.T, k)

scalar1, scalar2

(array([[-1.+1.j]]), array([[-1.+1.j]]))